name: Check updated weights

on:
  pull_request:
    # uncomment before merging
    # paths:
      # - 'runtime/*/src/weights/'

jobs:
  check_weights_files:
    strategy:
      fail-fast: false
      matrix:
        runtime: [westend, kusama, polkadot, rococo]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Check weights files
        shell: bash
        run: |
          scripts/ci/github/verify_updated_weights.sh ${{ matrix.runtime }}